export const quotes = [
  { text: 'You are what you do repeatedly.', author: 'Aristotle' },
  { text: 'He who has a why can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'No one is coming. That is the point.', author: '' },
  { text: 'Become the person you keep waiting for.', author: '' },
  { text: 'Your habits are your real ambition.', author: '' },
  { text: 'Standards beat motivation.', author: '' },
  { text: 'The work knows when you lied.', author: '' },
  { text: 'Comfort is a slow contract with regret.', author: '' },
  { text: 'Discipline is self-respect in action.', author: '' },
  { text: 'Do it tired. Do it unsure. Do it anyway.', author: '' },
  { text: 'You do not need more time. You need fewer excuses.', author: '' },
  { text: 'Your future is built when no one is watching.', author: '' },
  { text: 'Win the morning. Earn the night.', author: '' },
  { text: 'The version of you that wins is already watching.', author: '' },
  { text: 'Be harder to kill than your excuses.', author: '' },
  { text: 'Every skipped rep becomes evidence.', author: '' },
  { text: 'You are one decision from momentum.', author: '' },
  { text: 'Show up until showing up becomes identity.', author: '' },
  { text: 'Your potential is offended by your comfort.', author: '' },
  { text: 'The gap is not talent. The gap is consistency.', author: '' },
  { text: 'Act like your standards are watching.', author: '' },
  { text: 'Small promises kept become a different life.', author: '' },
  { text: 'You cannot become elite casually.', author: '' },
  { text: 'The hard thing is usually the honest thing.', author: '' },
  { text: 'Make discipline louder than doubt.', author: '' },
  { text: 'Your life follows what you repeat.', author: '' },
  { text: 'If it matters, it gets scheduled.', author: '' },
  { text: 'The body keeps receipts.', author: '' },
  { text: 'Do not negotiate with the weaker version of you.', author: '' },
  { text: 'You are training your future self right now.', author: '' },
  { text: 'Results prefer obsession to interest.', author: '' },
  { text: 'The best version of you is not convenient.', author: '' },
  { text: 'Earn confidence by keeping promises alone.', author: '' },
  { text: 'Your ceiling moves when your standards do.', author: '' },
  { text: 'Stop asking for easy. Ask for useful.', author: '' },
  { text: 'The work is the shortcut.', author: '' },
  { text: 'Be the proof you keep looking for.', author: '' },
  { text: 'You either build yourself or drift.', author: '' },
  { text: 'Make today hard enough to make tomorrow lighter.', author: '' },
  { text: 'The mirror does not care about intention.', author: '' },
  { text: 'Your discipline is your private reputation.', author: '' },
];

if (quotes.length === 0) {
  throw new Error('quotes: expected at least one entry.');
}
